### ISSUE TITLE
pyanalyze doesn't propagate initialisation through conditions involving walrus

### ISSUE THREAD

**Issue by hauntsaninja** [quora/pyanalyze#742] opened 2024-03-10 09:00 UTC
```
import os


def info(arg: str):
    if arg and (var := os.environ.get("ENV")):
        raise RuntimeError(f"{arg}: {var}")
```
gives me:
```
λ pyanalyze b.py

var may be used uninitialized (code: possibly_undefined_name)
In b.py at line 6
   3: 
   4: def info(arg: str):
   5:     if arg and (var := os.environ.get("ENV")):
   6:         raise RuntimeError(f"{arg}: {var}")
                                           ^
```

**Comment by JelleZijlstra** [comment] 2024-03-10 14:52
Duplicate of #597 

Thanks for these issues, I'll try to find some time to work on them

**Closed by JelleZijlstra** 2024-03-10 14:52 UTC
